[package]
name = "rust-openrtb"
version = "0.1.0"
authors = ["Guillaume Balaine <igosuki@gmail.com>"]
edition = "2018"

[dependencies]
json = "*"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"

bytes = "0.4"
futures = "0.1"
env_logger = "*"

actix = "0.7"
actix-web = "^0.7"
